/* ============================================================
   build-static.js — pre-render the whole site to build/
   ------------------------------------------------------------
   Produces a fully static, Cloudflare-Pages-ready copy of the
   site under build/. Every HTML page, feed and header file is
   generated by REUSING the exact code paths server.js serves at
   request time (renderHtml + feeds.js + the same discovered
   articles and asset map), so the static output is byte-identical
   to the live server's — modulo the per-deploy ?v= token.

   server.js is required (not run): requiring it builds the same
   article/asset state without starting the HTTP listener.

   Run:  npm run build:static   (after npm run build)
   Out:  build/   (Cloudflare Pages "output directory")
   ============================================================ */

"use strict";

const fs = require("fs");
const path = require("path");

const {
  renderHtml,
  VALID_ARTICLE_SLUGS,
  ARTICLES,
  ARTICLE_SCRIPTS,
  ASSET_MAP,
  SECURITY_HEADERS,
  SITE_CFG,
} = require("./server.js");
const { buildSitemap, buildRss, buildFeed } = require("./feeds.js");

const ROOT = __dirname;
const DEFAULT_OUT = path.join(ROOT, "build");

const DEPLOY_VERSION = process.env.CF_PAGES_COMMIT_SHA
  ? process.env.CF_PAGES_COMMIT_SHA.slice(0, 12)
  : String(Date.now());

// Any unknown path renders the same not-found page (computePageMeta's not-found
// branch ignores the requested pathname), so 404.html is route-independent.
const NOT_FOUND_ROUTE = "/this-route-does-not-exist";

// The fixed (non-article) HTML routes and their directory-index output paths.
const STATIC_HTML_ROUTES = [
  { pathname: "/", out: "index.html" },
  { pathname: "/i-scholi", out: "i-scholi/index.html" },
  { pathname: "/didaskontes", out: "didaskontes/index.html" },
  { pathname: "/diagonismoi", out: "diagonismoi/index.html" },
  { pathname: "/nea", out: "nea/index.html" },
  { pathname: "/epikoinonia", out: "epikoinonia/index.html" },
];

// Public root files copied verbatim (the dual modules + stylesheet + manifest).
const ROOT_PLAIN_FILES = [
  "styles.css",
  "site.config.js",
  "routes.js",
  "article-schema.js",
  "ui-helpers.js",
  "data.js",
  "site.webmanifest",
  "robots.txt",
];

// Root image bases — only the social share image lives at the root now.
const ROOT_IMAGE_FILES = ["og-image.jpg"];

// Asset directories copied whole (junk dotfiles excluded).
const ASSET_DIRS = ["vendor", "favicon", "brand", "images"];

// Excluded from the build entirely — source, tooling, config, docs and project
// material. Asserted absent from build/ at the end.
const MUST_BE_ABSENT = [
  "server.js",
  "build-static.js",
  "feeds.js",
  "package.json",
  "package-lock.json",
  ".gitignore",
  "LICENSE",
  "README.md",
  "news/README.md",
  "scripts",
  "test",
  "dist/manifest.json",
  "app.jsx",
  "icons.jsx",
  "components",
  // Project material that must never ship.
  "archive",
  "trash",
  "palette",
];

const isJunk = (src) => path.basename(src).startsWith(".");

function log(msg) { console.log(msg); }
function ensureDir(dir) { fs.mkdirSync(dir, { recursive: true }); }

function writeFile(outDir, relPath, contents) {
  const dest = path.join(outDir, relPath);
  ensureDir(path.dirname(dest));
  fs.writeFileSync(dest, contents);
}

function copyFile(outDir, relPath) {
  const src = path.join(ROOT, relPath);
  if (!fs.existsSync(src)) return false;
  const dest = path.join(outDir, relPath);
  ensureDir(path.dirname(dest));
  fs.copyFileSync(src, dest);
  return true;
}

// Copy an image plus its optimize-images siblings (.webp/.avif) when present.
function copyImage(outDir, relPath) {
  copyFile(outDir, relPath);
  const noExt = relPath.replace(/\.[^.]+$/, "");
  for (const ext of [".webp", ".avif"]) copyFile(outDir, noExt + ext);
}

// Recursively copy a directory (relative to ROOT), skipping junk dotfiles plus
// any path the optional `skip` predicate rejects.
function copyDir(outDir, relDir, skip) {
  const src = path.join(ROOT, relDir);
  if (!fs.existsSync(src)) return;
  fs.cpSync(src, path.join(outDir, relDir), {
    recursive: true,
    filter: (s) => !isJunk(s) && !(skip && skip(s)),
  });
}

// The _headers file: reproduce SECURITY_HEADERS verbatim plus all four cache
// classes. Cloudflare matches the REQUEST path, so the extensionless SPA routes
// are listed explicitly. Rules go general → specific so the intended value wins
// under both of Cloudflare's precedence models.
function buildHeadersFile(securityHeaders, htmlPathnames) {
  const NO_STORE = "Cache-Control: no-cache, no-store, must-revalidate";
  const lines = [];

  lines.push("/*");
  for (const [name, value] of Object.entries(securityHeaders)) {
    lines.push(`  ${name}: ${value}`);
  }
  lines.push("  Cache-Control: public, max-age=86400");
  lines.push("");

  for (const feed of ["/sitemap.xml", "/rss.xml", "/feed.json"]) {
    lines.push(feed);
    lines.push("  Cache-Control: public, max-age=3600");
    lines.push("");
  }

  lines.push("/dist/*");
  lines.push("  Cache-Control: public, max-age=31536000, immutable");
  lines.push("");

  lines.push("/*.html");
  lines.push(`  ${NO_STORE}`);
  lines.push("");
  for (const pathname of htmlPathnames) {
    lines.push(pathname);
    lines.push(`  ${NO_STORE}`);
    lines.push("");
  }

  return lines.join("\n");
}

function render(pathname) {
  return renderHtml(fs.readFileSync(path.join(ROOT, "index.html"), "utf8"), pathname, {
    deployVersion: DEPLOY_VERSION,
    articleScripts: ARTICLE_SCRIPTS,
    assetMap: ASSET_MAP,
  });
}

function assertNoExcluded(outDir) {
  const leaked = [];
  for (const rel of MUST_BE_ABSENT) {
    if (fs.existsSync(path.join(outDir, rel))) leaked.push(rel);
  }
  for (const entry of fs.readdirSync(outDir)) {
    if (entry.startsWith(".")) leaked.push(entry);
  }
  if (leaked.length) {
    throw new Error(`Excluded/private files leaked into build/: ${leaked.join(", ")}`);
  }
}

function buildStatic({ outDir = DEFAULT_OUT } = {}) {
  fs.rmSync(outDir, { recursive: true, force: true });
  ensureDir(outDir);

  const slugs = VALID_ARTICLE_SLUGS;

  // --- 1. Pre-render one HTML file per route to its directory-index path ----
  const htmlRoutes = [
    ...STATIC_HTML_ROUTES,
    ...slugs.map((slug) => ({ pathname: `/nea/${slug}`, out: `nea/${slug}/index.html` })),
  ];
  for (const route of htmlRoutes) {
    writeFile(outDir, route.out, render(route.pathname));
  }
  writeFile(outDir, "404.html", render(NOT_FOUND_ROUTE));

  // --- 2. Feeds (same builders the server uses) ----------------------------
  writeFile(outDir, "sitemap.xml", buildSitemap({ articles: ARTICLES, siteCfg: SITE_CFG }));
  writeFile(outDir, "rss.xml", buildRss({ articles: ARTICLES, siteCfg: SITE_CFG }));
  writeFile(outDir, "feed.json", buildFeed({ articles: ARTICLES, siteCfg: SITE_CFG }));

  // --- 3. Cloudflare config ------------------------------------------------
  writeFile(outDir, "_headers", buildHeadersFile(SECURITY_HEADERS, htmlRoutes.map((r) => r.pathname)));
  writeFile(outDir, "_redirects", "/index.html  /  301\n");

  // --- 4. Public assets ----------------------------------------------------
  for (const rel of ROOT_PLAIN_FILES) copyFile(outDir, rel);
  for (const rel of ROOT_IMAGE_FILES) copyImage(outDir, rel);
  for (const dir of ASSET_DIRS) copyDir(outDir, dir);
  // dist/ hashed bundles, but never the esbuild metafile.
  copyDir(outDir, "dist", (src) => path.basename(src) === "manifest.json");
  // Each discovered article folder ships whole: article.js + images.
  for (const slug of slugs) copyDir(outDir, path.join("news", slug));

  // --- 5. Safety: nothing private may have leaked in ------------------------
  assertNoExcluded(outDir);

  log(`Static build complete → ${path.relative(ROOT, outDir) || outDir}`);
  log(`  ${htmlRoutes.length} HTML pages + 404.html, ${slugs.length} articles`);
  return { outDir, htmlRoutes, slugs };
}

module.exports = { buildStatic, DEPLOY_VERSION };

if (require.main === module) {
  buildStatic();
}
